//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cns.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloseTicketCheckDiscount
    {
        public System.Guid CustumerId { get; set; }
        public System.Guid CloseTicketCheckcCustomer { get; set; }
        public System.Guid DiscountCardsCustumerId { get; set; }
        public string DCBC { get; set; }
        public Nullable<int> DCBC_BiloPoints { get; set; }
        public Nullable<int> DCBC_DobavilePoints { get; set; }
        public Nullable<int> DCBC_OtnayliPoints { get; set; }
        public Nullable<int> DCBC_OstalosPoints { get; set; }
        public string DCBC_name { get; set; }
    }
}
