//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cns.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCards
    {
        public System.Guid custumerId { get; set; }
        public string numberCard { get; set; }
        public Nullable<int> points { get; set; }
        public bool Active { get; set; }
        public Nullable<System.Guid> InfoClients_custumerId { get; set; }
        public Nullable<System.DateTime> DateTimeLastAddProduct { get; set; }
    }
}
