//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevisWeb
    {
        public System.Guid CustomerId { get; set; }
        public int IdDevis { get; set; }
        public decimal PrixHT { get; set; }
        public decimal MonPrixHT { get; set; }
        public decimal QTY { get; set; }
        public decimal TotalHT { get; set; }
        public short PayementType { get; set; }
        public bool Operator { get; set; }
        public System.Guid ProductsCustumerId { get; set; }
        public System.Guid InfoClients_custumerId { get; set; }
    
        public virtual InfoClients InfoClients { get; set; }
        public virtual Products Products { get; set; }
    }
}
