//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevisId
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.Guid> infoClientsCustomerId { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
