//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrpProductSet
    {
        public GrpProductSet()
        {
            this.SubGrpNameSet = new HashSet<SubGrpNameSet>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<SubGrpNameSet> SubGrpNameSet { get; set; }
    }
}
