//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoClients
    {
        public InfoClients()
        {
            this.DevisWeb = new HashSet<DevisWeb>();
        }
    
        public System.Guid custumerId { get; set; }
        public int TypeClient { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string NameCompany { get; set; }
        public string SIRET { get; set; }
        public string FRTVA { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficeZipCode { get; set; }
        public string OfficeCity { get; set; }
        public string HomeAddress { get; set; }
        public string HomeZipCode { get; set; }
        public string HomeCity { get; set; }
        public string Telephone { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public System.Guid Countrys_CustomerId { get; set; }
        public System.Guid FavoritesProductAutoCustomerId { get; set; }
        public string Nclient { get; set; }
    
        public virtual ICollection<DevisWeb> DevisWeb { get; set; }
    }
}
