//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsWeb
    {
        public ProductsWeb()
        {
            this.Products = new HashSet<Products>();
        }
    
        public System.Guid CustomerId { get; set; }
        public bool Visible { get; set; }
        public string Images { get; set; }
        public string DescrCourt { get; set; }
        public string DescrLong { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> UniteVolume { get; set; }
        public Nullable<decimal> ContenanceBox { get; set; }
        public Nullable<decimal> ContenancePallet { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<bool> Frozen { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
