//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsBC
    {
        public System.Guid CustomerId { get; set; }
        public System.Guid CustomerIdProduct { get; set; }
        public string CodeBar { get; set; }
        public decimal QTY { get; set; }
        public string Description { get; set; }
    }
}
