//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.DevisWeb = new HashSet<DevisWeb>();
            this.StockReal = new HashSet<StockReal>();
        }
    
        public System.Guid CustumerId { get; set; }
        public string Name { get; set; }
        public string CodeBare { get; set; }
        public string Desc { get; set; }
        public short Chp_cat { get; set; }
        public bool Balance { get; set; }
        public decimal Contenance { get; set; }
        public int UniteContenance { get; set; }
        public int Tare { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid TVACustumerId { get; set; }
        public System.Guid ProductsWeb_CustomerId { get; set; }
        public int SubGrpProduct_Id { get; set; }
        public Nullable<System.Guid> FavoritesProductCustomerId { get; set; }
    
        public virtual ICollection<DevisWeb> DevisWeb { get; set; }
        public virtual ProductsWeb ProductsWeb { get; set; }
        public virtual ICollection<StockReal> StockReal { get; set; }
        public virtual SubGrpNameSet SubGrpNameSet { get; set; }
        public virtual TVA TVA { get; set; }
    }
}
