//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReal
    {
        public System.Guid CustomerId { get; set; }
        public decimal QTY { get; set; }
        public decimal MinQTY { get; set; }
        public decimal Price { get; set; }
        public System.Guid ProductsCustumerId { get; set; }
        public System.Guid Establishment_CustomerId { get; set; }
    
        public virtual Establishment Establishment { get; set; }
        public virtual Products Products { get; set; }
    }
}
