//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslateUniteContenance
    {
        public System.Guid CustomerId { get; set; }
        public int IdUnite { get; set; }
        public string cod_lng { get; set; }
        public string nameUnite { get; set; }
    }
}
