//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply filter.
        /// </summary>
        public static string BtnApplyFilter {
            get {
                return ResourceManager.GetString("BtnApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel PRO mode.
        /// </summary>
        public static string BtnCancelProMode {
            get {
                return ResourceManager.GetString("BtnCancelProMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        public static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close local.
        /// </summary>
        public static string BtnCloseLocal {
            get {
                return ResourceManager.GetString("BtnCloseLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close total.
        /// </summary>
        public static string BtnCloseTotal {
            get {
                return ResourceManager.GetString("BtnCloseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Del..
        /// </summary>
        public static string BtnDel {
            get {
                return ResourceManager.GetString("BtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter.
        /// </summary>
        public static string BtnEnter {
            get {
                return ResourceManager.GetString("BtnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Force close.
        /// </summary>
        public static string BtnForceClose {
            get {
                return ResourceManager.GetString("BtnForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full update.
        /// </summary>
        public static string BtnFullUpdate {
            get {
                return ResourceManager.GetString("BtnFullUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log In.
        /// </summary>
        public static string BtnLogon {
            get {
                return ResourceManager.GetString("BtnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New PRO.
        /// </summary>
        public static string BtnNewPro {
            get {
                return ResourceManager.GetString("BtnNewPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open local.
        /// </summary>
        public static string BtnOpenLocal {
            get {
                return ResourceManager.GetString("BtnOpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open total.
        /// </summary>
        public static string BtnOpenTotal {
            get {
                return ResourceManager.GetString("BtnOpenTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Previous.
        /// </summary>
        public static string BtnPrev {
            get {
                return ResourceManager.GetString("BtnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print duplicate.
        /// </summary>
        public static string BtnPrintDuplicate {
            get {
                return ResourceManager.GetString("BtnPrintDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Redact.
        /// </summary>
        public static string BtnRedact {
            get {
                return ResourceManager.GetString("BtnRedact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove row.
        /// </summary>
        public static string BtnRemoveRow {
            get {
                return ResourceManager.GetString("BtnRemoveRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reweigh.
        /// </summary>
        public static string BtnReweigh {
            get {
                return ResourceManager.GetString("BtnReweigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activate.
        /// </summary>
        public static string BtnToActive {
            get {
                return ResourceManager.GetString("BtnToActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deactivate.
        /// </summary>
        public static string BtnToDeactive {
            get {
                return ResourceManager.GetString("BtnToDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ChpCat {
            get {
                return ResourceManager.GetString("ChpCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ChpCat_s {
            get {
                return ResourceManager.GetString("ChpCat_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ChpFam {
            get {
                return ResourceManager.GetString("ChpFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ChpFam_s {
            get {
                return ResourceManager.GetString("ChpFam_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ChpssFam_s {
            get {
                return ResourceManager.GetString("ChpssFam_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculator.
        /// </summary>
        public static string FuncCalculator {
            get {
                return ResourceManager.GetString("FuncCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel bay.
        /// </summary>
        public static string FuncCancelBay {
            get {
                return ResourceManager.GetString("FuncCancelBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Case products.
        /// </summary>
        public static string FuncCaseProducts {
            get {
                return ResourceManager.GetString("FuncCaseProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear products.
        /// </summary>
        public static string FuncClearProducts {
            get {
                return ResourceManager.GetString("FuncClearProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close cashbox.
        /// </summary>
        public static string FuncCloseCashbox {
            get {
                return ResourceManager.GetString("FuncCloseCashbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete product.
        /// </summary>
        public static string FuncDelProduct {
            get {
                return ResourceManager.GetString("FuncDelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discount cards.
        /// </summary>
        public static string FuncDiscountCard {
            get {
                return ResourceManager.GetString("FuncDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset discount.
        /// </summary>
        public static string FuncDiscountReset {
            get {
                return ResourceManager.GetString("FuncDiscountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit price.
        /// </summary>
        public static string FuncEditPrice {
            get {
                return ResourceManager.GetString("FuncEditPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit product.
        /// </summary>
        public static string FuncEditProduct {
            get {
                return ResourceManager.GetString("FuncEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на History.
        /// </summary>
        public static string FuncHistory {
            get {
                return ResourceManager.GetString("FuncHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checks history.
        /// </summary>
        public static string FuncHistoryChecks {
            get {
                return ResourceManager.GetString("FuncHistoryChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards history.
        /// </summary>
        public static string FuncHistoryOfAllCards {
            get {
                return ResourceManager.GetString("FuncHistoryOfAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open cashbox.
        /// </summary>
        public static string FuncOpenCashBox {
            get {
                return ResourceManager.GetString("FuncOpenCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Payment method.
        /// </summary>
        public static string FuncPaymentMethod {
            get {
                return ResourceManager.GetString("FuncPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product menu.
        /// </summary>
        public static string FuncProductMenu {
            get {
                return ResourceManager.GetString("FuncProductMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset btn.
        /// </summary>
        public static string FuncResetBtn {
            get {
                return ResourceManager.GetString("FuncResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Return product.
        /// </summary>
        public static string FuncReturnProduct {
            get {
                return ResourceManager.GetString("FuncReturnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set barcode.
        /// </summary>
        public static string FuncSetBarCode {
            get {
                return ResourceManager.GetString("FuncSetBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show pro.
        /// </summary>
        public static string FuncShowPro {
            get {
                return ResourceManager.GetString("FuncShowPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To pro.
        /// </summary>
        public static string FuncToPro {
            get {
                return ResourceManager.GetString("FuncToPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show total.
        /// </summary>
        public static string FuncTotal {
            get {
                return ResourceManager.GetString("FuncTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To wait.
        /// </summary>
        public static string FuncToWait {
            get {
                return ResourceManager.GetString("FuncToWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update DB.
        /// </summary>
        public static string FuncUpdateDB {
            get {
                return ResourceManager.GetString("FuncUpdateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn.
        /// </summary>
        public static string FunTurn {
            get {
                return ResourceManager.GetString("FunTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already closing.
        /// </summary>
        public static string LabelAlreadyClosing {
            get {
                return ResourceManager.GetString("LabelAlreadyClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Already closing general.
        /// </summary>
        public static string LabelAlreadyGeneralClosing {
            get {
                return ResourceManager.GetString("LabelAlreadyGeneralClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelB {
            get {
                return ResourceManager.GetString("LabelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balance.
        /// </summary>
        public static string LabelBalance {
            get {
                return ResourceManager.GetString("LabelBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balance kg.
        /// </summary>
        public static string LabelBalanceKg {
            get {
                return ResourceManager.GetString("LabelBalanceKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barcode.
        /// </summary>
        public static string LabelBarcode {
            get {
                return ResourceManager.GetString("LabelBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color of button.
        /// </summary>
        public static string LabelButtonColor {
            get {
                return ResourceManager.GetString("LabelButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of button.
        /// </summary>
        public static string LabelButtonName {
            get {
                return ResourceManager.GetString("LabelButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card number.
        /// </summary>
        public static string LabelCardNumber {
            get {
                return ResourceManager.GetString("LabelCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cashbox.
        /// </summary>
        public static string LabelCashBox {
            get {
                return ResourceManager.GetString("LabelCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The time of the Caisse.
        /// </summary>
        public static string LabelCashBoxDate {
            get {
                return ResourceManager.GetString("LabelCashBoxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The cashbox is closed.
        /// </summary>
        public static string LabelCashBoxIsClosed {
            get {
                return ResourceManager.GetString("LabelCashBoxIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cashbox time.
        /// </summary>
        public static string LabelCashboxTime {
            get {
                return ResourceManager.GetString("LabelCashboxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cashbox data.
        /// </summary>
        public static string LabelCassieData {
            get {
                return ResourceManager.GetString("LabelCassieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelCB {
            get {
                return ResourceManager.GetString("LabelCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check.
        /// </summary>
        public static string LabelCheck {
            get {
                return ResourceManager.GetString("LabelCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Checks tickets.
        /// </summary>
        public static string LabelCheckTicket {
            get {
                return ResourceManager.GetString("LabelCheckTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temp checks tickets.
        /// </summary>
        public static string LabelCheckTicketTmp {
            get {
                return ResourceManager.GetString("LabelCheckTicketTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clients.
        /// </summary>
        public static string LabelClientInfo {
            get {
                return ResourceManager.GetString("LabelClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closing completed.
        /// </summary>
        public static string LabelCloseEnd {
            get {
                return ResourceManager.GetString("LabelCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close tickets.
        /// </summary>
        public static string LabelCloseTicket {
            get {
                return ResourceManager.GetString("LabelCloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company name.
        /// </summary>
        public static string LabelCompanyName {
            get {
                return ResourceManager.GetString("LabelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test connection.
        /// </summary>
        public static string LabelConnectionTest {
            get {
                return ResourceManager.GetString("LabelConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contenance.
        /// </summary>
        public static string LabelContenance {
            get {
                return ResourceManager.GetString("LabelContenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating the product button.
        /// </summary>
        public static string LabelCreateProductButton {
            get {
                return ResourceManager.GetString("LabelCreateProductButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string LabelCurrency {
            get {
                return ResourceManager.GetString("LabelCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error - the date has not changed! Restart in administrator mode.
        /// </summary>
        public static string LabelDataError {
            get {
                return ResourceManager.GetString("LabelDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loading.
        /// </summary>
        public static string LabelDataLoading {
            get {
                return ResourceManager.GetString("LabelDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date updated.
        /// </summary>
        public static string LabelDateUpdate {
            get {
                return ResourceManager.GetString("LabelDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web.
        /// </summary>
        public static string LabelDevisWeb {
            get {
                return ResourceManager.GetString("LabelDevisWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discount.
        /// </summary>
        public static string LabelDiscount {
            get {
                return ResourceManager.GetString("LabelDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Discount cards.
        /// </summary>
        public static string LabelDiscountCard {
            get {
                return ResourceManager.GetString("LabelDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EAN Barcode already exists.
        /// </summary>
        public static string LabelEanAlreadyExists {
            get {
                return ResourceManager.GetString("LabelEanAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please first edit the list products.
        /// </summary>
        public static string LabelEditListProducts {
            get {
                return ResourceManager.GetString("LabelEditListProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error closing.
        /// </summary>
        public static string LabelErrorClosing {
            get {
                return ResourceManager.GetString("LabelErrorClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error general closing.
        /// </summary>
        public static string LabelErrorGeneralClosing {
            get {
                return ResourceManager.GetString("LabelErrorGeneralClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelEst {
            get {
                return ResourceManager.GetString("LabelEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excess.
        /// </summary>
        public static string LabelExcess {
            get {
                return ResourceManager.GetString("LabelExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full name.
        /// </summary>
        public static string LabelFIO {
            get {
                return ResourceManager.GetString("LabelFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Function.
        /// </summary>
        public static string LabelFunction {
            get {
                return ResourceManager.GetString("LabelFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General closing completed.
        /// </summary>
        public static string LabelGeneralCloseEnd {
            get {
                return ResourceManager.GetString("LabelGeneralCloseEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group.
        /// </summary>
        public static string LabelGroup {
            get {
                return ResourceManager.GetString("LabelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supreme.
        /// </summary>
        public static string LabelHighter {
            get {
                return ResourceManager.GetString("LabelHighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home address.
        /// </summary>
        public static string LabelHomeAddress {
            get {
                return ResourceManager.GetString("LabelHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home city.
        /// </summary>
        public static string LabelHomeCity {
            get {
                return ResourceManager.GetString("LabelHomeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home ZIP code.
        /// </summary>
        public static string LabelHomeIndex {
            get {
                return ResourceManager.GetString("LabelHomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image.
        /// </summary>
        public static string LabelImage {
            get {
                return ResourceManager.GetString("LabelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Important functions.
        /// </summary>
        public static string LabelImportantFunctions {
            get {
                return ResourceManager.GetString("LabelImportantFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на incorrect.
        /// </summary>
        public static string LabelIncorrect {
            get {
                return ResourceManager.GetString("LabelIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid EAN Barcode.
        /// </summary>
        public static string LabelIncorrectEAN {
            get {
                return ResourceManager.GetString("LabelIncorrectEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Taxpayer identification number.
        /// </summary>
        public static string LabelINN {
            get {
                return ResourceManager.GetString("LabelINN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In memory.
        /// </summary>
        public static string LabelInputInMemory {
            get {
                return ResourceManager.GetString("LabelInputInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number format is invalid.
        /// </summary>
        public static string LabelInvalidNumberFormat {
            get {
                return ResourceManager.GetString("LabelInvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activity of cards.
        /// </summary>
        public static string LabelIsActive {
            get {
                return ResourceManager.GetString("LabelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not active.
        /// </summary>
        public static string LabelIsActiveFalse {
            get {
                return ResourceManager.GetString("LabelIsActiveFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        public static string LabelIsActiveTrue {
            get {
                return ResourceManager.GetString("LabelIsActiveTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelLocalOpeningKey {
            get {
                return ResourceManager.GetString("LabelLocalOpeningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect login or password.
        /// </summary>
        public static string LabelLogonError {
            get {
                return ResourceManager.GetString("LabelLogonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string LabelMail {
            get {
                return ResourceManager.GetString("LabelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max.
        /// </summary>
        public static string LabelMax {
            get {
                return ResourceManager.GetString("LabelMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This product name already exists.
        /// </summary>
        public static string LabelNameAlreadyExists {
            get {
                return ResourceManager.GetString("LabelNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nation.
        /// </summary>
        public static string LabelNameNation {
            get {
                return ResourceManager.GetString("LabelNameNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string LabelNameOfFIO {
            get {
                return ResourceManager.GetString("LabelNameOfFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name place arround.
        /// </summary>
        public static string LabelNamePlaceArround {
            get {
                return ResourceManager.GetString("LabelNamePlaceArround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must fill groups and subgroups.
        /// </summary>
        public static string LabelNeedInputGroupsAndSubgroups {
            get {
                return ResourceManager.GetString("LabelNeedInputGroupsAndSubgroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Must fill out VAT.
        /// </summary>
        public static string LabelNeedInputNds {
            get {
                return ResourceManager.GetString("LabelNeedInputNds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string LabelNew {
            get {
                return ResourceManager.GetString("LabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New total.
        /// </summary>
        public static string LabelNewTotal {
            get {
                return ResourceManager.GetString("LabelNewTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found.
        /// </summary>
        public static string LabelNofFound {
            get {
                return ResourceManager.GetString("LabelNofFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not enough money.
        /// </summary>
        public static string LabelNotEnoughMoney {
            get {
                return ResourceManager.GetString("LabelNotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not have permission.
        /// </summary>
        public static string LabelNotPermission {
            get {
                return ResourceManager.GetString("LabelNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Now.
        /// </summary>
        public static string LabelNow {
            get {
                return ResourceManager.GetString("LabelNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N° cashbox.
        /// </summary>
        public static string LabelNumberCashBox {
            get {
                return ResourceManager.GetString("LabelNumberCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на N° check.
        /// </summary>
        public static string LabelNumberCheck {
            get {
                return ResourceManager.GetString("LabelNumberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NumPad.
        /// </summary>
        public static string LabelNumpad {
            get {
                return ResourceManager.GetString("LabelNumpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Old.
        /// </summary>
        public static string LabelOld {
            get {
                return ResourceManager.GetString("LabelOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string LabelOpen {
            get {
                return ResourceManager.GetString("LabelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened.
        /// </summary>
        public static string LabelOpened {
            get {
                return ResourceManager.GetString("LabelOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opened by.
        /// </summary>
        public static string LabelOpenedBy {
            get {
                return ResourceManager.GetString("LabelOpenedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смена открыта.
        /// </summary>
        public static string LabelOpenLocal {
            get {
                return ResourceManager.GetString("LabelOpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Касса открыта.
        /// </summary>
        public static string LabelOpenTotalTW {
            get {
                return ResourceManager.GetString("LabelOpenTotalTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation complete.
        /// </summary>
        public static string LabelOperationComplete {
            get {
                return ResourceManager.GetString("LabelOperationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Means of payment.
        /// </summary>
        public static string LabelPaymentMeans {
            get {
                return ResourceManager.GetString("LabelPaymentMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pay products.
        /// </summary>
        public static string LabelPayProduct {
            get {
                return ResourceManager.GetString("LabelPayProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temp pay products.
        /// </summary>
        public static string LabelPayProductTmp {
            get {
                return ResourceManager.GetString("LabelPayProductTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permissions.
        /// </summary>
        public static string LabelPermissions {
            get {
                return ResourceManager.GetString("LabelPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The piece(s) can not be a fractional number.
        /// </summary>
        public static string LabelPieceNotFractional {
            get {
                return ResourceManager.GetString("LabelPieceNotFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Piece or kg.
        /// </summary>
        public static string LabelPieceOrKg {
            get {
                return ResourceManager.GetString("LabelPieceOrKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pin code.
        /// </summary>
        public static string LabelPin {
            get {
                return ResourceManager.GetString("LabelPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait while loading !.
        /// </summary>
        public static string LabelPleaseWaitWhileLoading {
            get {
                return ResourceManager.GetString("LabelPleaseWaitWhileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Points.
        /// </summary>
        public static string LabelPoints {
            get {
                return ResourceManager.GetString("LabelPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelPost {
            get {
                return ResourceManager.GetString("LabelPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postal code.
        /// </summary>
        public static string LabelPostalCode {
            get {
                return ResourceManager.GetString("LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price with VAT.
        /// </summary>
        public static string LabelPrixTTC {
            get {
                return ResourceManager.GetString("LabelPrixTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product.
        /// </summary>
        public static string LabelProduct {
            get {
                return ResourceManager.GetString("LabelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product not found.
        /// </summary>
        public static string LabelProductNotFind {
            get {
                return ResourceManager.GetString("LabelProductNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product removed.
        /// </summary>
        public static string LabelProductRemoved {
            get {
                return ResourceManager.GetString("LabelProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        public static string LabelProducts {
            get {
                return ResourceManager.GetString("LabelProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Providers.
        /// </summary>
        public static string LabelProviders {
            get {
                return ResourceManager.GetString("LabelProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на QTY.
        /// </summary>
        public static string LabelQty {
            get {
                return ResourceManager.GetString("LabelQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Question.
        /// </summary>
        public static string LabelQuestion {
            get {
                return ResourceManager.GetString("LabelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rest.
        /// </summary>
        public static string LabelRest {
            get {
                return ResourceManager.GetString("LabelRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role.
        /// </summary>
        public static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search by EAN bar code.
        /// </summary>
        public static string LabelSearchByEAN {
            get {
                return ResourceManager.GetString("LabelSearchByEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select product.
        /// </summary>
        public static string LabelSelectProduct {
            get {
                return ResourceManager.GetString("LabelSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server time.
        /// </summary>
        public static string LabelServerTime {
            get {
                return ResourceManager.GetString("LabelServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stock.
        /// </summary>
        public static string LabelStock {
            get {
                return ResourceManager.GetString("LabelStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity in stock.
        /// </summary>
        public static string LabelStockCount {
            get {
                return ResourceManager.GetString("LabelStockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subgroup.
        /// </summary>
        public static string LabelSubgroup {
            get {
                return ResourceManager.GetString("LabelSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount is exceeded.
        /// </summary>
        public static string LabelSummIsExceed {
            get {
                return ResourceManager.GetString("LabelSummIsExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surname.
        /// </summary>
        public static string LabelSurnameOfFIO {
            get {
                return ResourceManager.GetString("LabelSurnameOfFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Synchronization in progress, left later.
        /// </summary>
        public static string LabelSyncProcess {
            get {
                return ResourceManager.GetString("LabelSyncProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tare.
        /// </summary>
        public static string LabelTare {
            get {
                return ResourceManager.GetString("LabelTare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color of text.
        /// </summary>
        public static string LabelTextColor {
            get {
                return ResourceManager.GetString("LabelTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelTicketR {
            get {
                return ResourceManager.GetString("LabelTicketR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelTicketRetour {
            get {
                return ResourceManager.GetString("LabelTicketRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total.
        /// </summary>
        public static string LabelTotal {
            get {
                return ResourceManager.GetString("LabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string LabelTotalOpeningKey {
            get {
                return ResourceManager.GetString("LabelTotalOpeningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customer type.
        /// </summary>
        public static string LabelTypeClient {
            get {
                return ResourceManager.GetString("LabelTypeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pays types.
        /// </summary>
        public static string LabelTypesPays {
            get {
                return ResourceManager.GetString("LabelTypesPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of VAT.
        /// </summary>
        public static string LabelTypeVat {
            get {
                return ResourceManager.GetString("LabelTypeVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unit contenance.
        /// </summary>
        public static string LabelUnitContenance {
            get {
                return ResourceManager.GetString("LabelUnitContenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VAT.
        /// </summary>
        public static string LabelVat {
            get {
                return ResourceManager.GetString("LabelVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewing.
        /// </summary>
        public static string LabelViewing {
            get {
                return ResourceManager.GetString("LabelViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office address.
        /// </summary>
        public static string LabelWorkAddress {
            get {
                return ResourceManager.GetString("LabelWorkAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office city.
        /// </summary>
        public static string LabelWorkCity {
            get {
                return ResourceManager.GetString("LabelWorkCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office ZIP code.
        /// </summary>
        public static string LabelWorkIndex {
            get {
                return ResourceManager.GetString("LabelWorkIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write-off.
        /// </summary>
        public static string LabelWriteOff {
            get {
                return ResourceManager.GetString("LabelWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Files.
        /// </summary>
        public static string LabelXmlFile {
            get {
                return ResourceManager.GetString("LabelXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group products.
        /// </summary>
        public static string MenuGroupsProduct {
            get {
                return ResourceManager.GetString("MenuGroupsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roles.
        /// </summary>
        public static string MenuRoles {
            get {
                return ResourceManager.GetString("MenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync settings.
        /// </summary>
        public static string MenuSyncSetting {
            get {
                return ResourceManager.GetString("MenuSyncSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VATs.
        /// </summary>
        public static string MenuVats {
            get {
                return ResourceManager.GetString("MenuVats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сonfirm the deletion.
        /// </summary>
        public static string MessageDeleteQuestion {
            get {
                return ResourceManager.GetString("MessageDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is administrator.
        /// </summary>
        public static string MessageIsAdmin {
            get {
                return ResourceManager.GetString("MessageIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permit all.
        /// </summary>
        public static string PermissionAll {
            get {
                return ResourceManager.GetString("PermissionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission delete product from check.
        /// </summary>
        public static string PermissionDeleteProductFromCheck {
            get {
                return ResourceManager.GetString("PermissionDeleteProductFromCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission editing of buttons.
        /// </summary>
        public static string PermissionRedactButton {
            get {
                return ResourceManager.GetString("PermissionRedactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission editing groups of products.
        /// </summary>
        public static string PermissionRedactGroupsProduct {
            get {
                return ResourceManager.GetString("PermissionRedactGroupsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission editing of roles.
        /// </summary>
        public static string PermissionRedactRole {
            get {
                return ResourceManager.GetString("PermissionRedactRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission to change the number of items in stock.
        /// </summary>
        public static string PermissionRedactStockCount {
            get {
                return ResourceManager.GetString("PermissionRedactStockCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit sync settings.
        /// </summary>
        public static string PermissionRedactSync {
            get {
                return ResourceManager.GetString("PermissionRedactSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission editing of users.
        /// </summary>
        public static string PermissionRedactUser {
            get {
                return ResourceManager.GetString("PermissionRedactUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission editing VAT.
        /// </summary>
        public static string PermissionRedactVat {
            get {
                return ResourceManager.GetString("PermissionRedactVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission Write-off.
        /// </summary>
        public static string PermissionWriteOff {
            get {
                return ResourceManager.GetString("PermissionWriteOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Functions of cashbox.
        /// </summary>
        public static string TabCashFunctions {
            get {
                return ResourceManager.GetString("TabCashFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Display settings.
        /// </summary>
        public static string TabDisplaySettings {
            get {
                return ResourceManager.GetString("TabDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Products.
        /// </summary>
        public static string TabProducts {
            get {
                return ResourceManager.GetString("TabProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick payment methods.
        /// </summary>
        public static string TabQuickPaymentsMethods {
            get {
                return ResourceManager.GetString("TabQuickPaymentsMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank card.
        /// </summary>
        public static string TypePayBankCards {
            get {
                return ResourceManager.GetString("TypePayBankCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check.
        /// </summary>
        public static string TypePayBankChecks {
            get {
                return ResourceManager.GetString("TypePayBankChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bond.
        /// </summary>
        public static string TypePayBondAchat {
            get {
                return ResourceManager.GetString("TypePayBondAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cash.
        /// </summary>
        public static string TypePayCash {
            get {
                return ResourceManager.GetString("TypePayCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resto card.
        /// </summary>
        public static string TypePayResto {
            get {
                return ResourceManager.GetString("TypePayResto", resourceCulture);
            }
        }
    }
}
