//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter.
        /// </summary>
        public static string BtnApplyFilter {
            get {
                return ResourceManager.GetString("BtnApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel PRO mode.
        /// </summary>
        public static string BtnCancelProMode {
            get {
                return ResourceManager.GetString("BtnCancelProMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string BtnClear {
            get {
                return ResourceManager.GetString("BtnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close local.
        /// </summary>
        public static string BtnCloseLocal {
            get {
                return ResourceManager.GetString("BtnCloseLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close total.
        /// </summary>
        public static string BtnCloseTotal {
            get {
                return ResourceManager.GetString("BtnCloseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del..
        /// </summary>
        public static string BtnDel {
            get {
                return ResourceManager.GetString("BtnDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string BtnEnter {
            get {
                return ResourceManager.GetString("BtnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force close.
        /// </summary>
        public static string BtnForceClose {
            get {
                return ResourceManager.GetString("BtnForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full update.
        /// </summary>
        public static string BtnFullUpdate {
            get {
                return ResourceManager.GetString("BtnFullUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string BtnLogon {
            get {
                return ResourceManager.GetString("BtnLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PRO.
        /// </summary>
        public static string BtnNewPro {
            get {
                return ResourceManager.GetString("BtnNewPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open local.
        /// </summary>
        public static string BtnOpenLocal {
            get {
                return ResourceManager.GetString("BtnOpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open total.
        /// </summary>
        public static string BtnOpenTotal {
            get {
                return ResourceManager.GetString("BtnOpenTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string BtnPrev {
            get {
                return ResourceManager.GetString("BtnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string BtnPrint {
            get {
                return ResourceManager.GetString("BtnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print duplicate.
        /// </summary>
        public static string BtnPrintDuplicate {
            get {
                return ResourceManager.GetString("BtnPrintDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redact.
        /// </summary>
        public static string BtnRedact {
            get {
                return ResourceManager.GetString("BtnRedact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove row.
        /// </summary>
        public static string BtnRemoveRow {
            get {
                return ResourceManager.GetString("BtnRemoveRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reweigh.
        /// </summary>
        public static string BtnReweigh {
            get {
                return ResourceManager.GetString("BtnReweigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChpCat {
            get {
                return ResourceManager.GetString("ChpCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChpCat_s {
            get {
                return ResourceManager.GetString("ChpCat_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChpFam {
            get {
                return ResourceManager.GetString("ChpFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChpFam_s {
            get {
                return ResourceManager.GetString("ChpFam_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChpssFam_s {
            get {
                return ResourceManager.GetString("ChpssFam_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string FuncCalculator {
            get {
                return ResourceManager.GetString("FuncCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel bay.
        /// </summary>
        public static string FuncCancelBay {
            get {
                return ResourceManager.GetString("FuncCancelBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case products.
        /// </summary>
        public static string FuncCaseProducts {
            get {
                return ResourceManager.GetString("FuncCaseProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear products.
        /// </summary>
        public static string FuncClearProducts {
            get {
                return ResourceManager.GetString("FuncClearProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close cashbox.
        /// </summary>
        public static string FuncCloseCashbox {
            get {
                return ResourceManager.GetString("FuncCloseCashbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string FuncDelProduct {
            get {
                return ResourceManager.GetString("FuncDelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cards.
        /// </summary>
        public static string FuncDiscountCard {
            get {
                return ResourceManager.GetString("FuncDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset discount.
        /// </summary>
        public static string FuncDiscountReset {
            get {
                return ResourceManager.GetString("FuncDiscountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit price.
        /// </summary>
        public static string FuncEditPrice {
            get {
                return ResourceManager.GetString("FuncEditPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string FuncEditProduct {
            get {
                return ResourceManager.GetString("FuncEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string FuncHistory {
            get {
                return ResourceManager.GetString("FuncHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks history.
        /// </summary>
        public static string FuncHistoryChecks {
            get {
                return ResourceManager.GetString("FuncHistoryChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards history.
        /// </summary>
        public static string FuncHistoryOfAllCards {
            get {
                return ResourceManager.GetString("FuncHistoryOfAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open cashbox.
        /// </summary>
        public static string FuncOpenCashBox {
            get {
                return ResourceManager.GetString("FuncOpenCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string FuncPaymentMethod {
            get {
                return ResourceManager.GetString("FuncPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product menu.
        /// </summary>
        public static string FuncProductMenu {
            get {
                return ResourceManager.GetString("FuncProductMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset btn.
        /// </summary>
        public static string FuncResetBtn {
            get {
                return ResourceManager.GetString("FuncResetBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return product.
        /// </summary>
        public static string FuncReturnProduct {
            get {
                return ResourceManager.GetString("FuncReturnProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set barcode.
        /// </summary>
        public static string FuncSetBarCode {
            get {
                return ResourceManager.GetString("FuncSetBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show pro.
        /// </summary>
        public static string FuncShowPro {
            get {
                return ResourceManager.GetString("FuncShowPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To pro.
        /// </summary>
        public static string FuncToPro {
            get {
                return ResourceManager.GetString("FuncToPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show total.
        /// </summary>
        public static string FuncTotal {
            get {
                return ResourceManager.GetString("FuncTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To wait.
        /// </summary>
        public static string FuncToWait {
            get {
                return ResourceManager.GetString("FuncToWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update DB.
        /// </summary>
        public static string FuncUpdateDB {
            get {
                return ResourceManager.GetString("FuncUpdateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn.
        /// </summary>
        public static string FunTurn {
            get {
                return ResourceManager.GetString("FunTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelB {
            get {
                return ResourceManager.GetString("LabelB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string LabelBalance {
            get {
                return ResourceManager.GetString("LabelBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance kg.
        /// </summary>
        public static string LabelBalanceKg {
            get {
                return ResourceManager.GetString("LabelBalanceKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string LabelBarcode {
            get {
                return ResourceManager.GetString("LabelBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of button.
        /// </summary>
        public static string LabelButtonColor {
            get {
                return ResourceManager.GetString("LabelButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of button.
        /// </summary>
        public static string LabelButtonName {
            get {
                return ResourceManager.GetString("LabelButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashbox.
        /// </summary>
        public static string LabelCashBox {
            get {
                return ResourceManager.GetString("LabelCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time of the Caisse.
        /// </summary>
        public static string LabelCashBoxDate {
            get {
                return ResourceManager.GetString("LabelCashBoxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashbox time.
        /// </summary>
        public static string LabelCashboxTime {
            get {
                return ResourceManager.GetString("LabelCashboxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashbox data.
        /// </summary>
        public static string LabelCassieData {
            get {
                return ResourceManager.GetString("LabelCassieData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelCB {
            get {
                return ResourceManager.GetString("LabelCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string LabelCheck {
            get {
                return ResourceManager.GetString("LabelCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks tickets.
        /// </summary>
        public static string LabelCheckTicket {
            get {
                return ResourceManager.GetString("LabelCheckTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp checks tickets.
        /// </summary>
        public static string LabelCheckTicketTmp {
            get {
                return ResourceManager.GetString("LabelCheckTicketTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string LabelClientInfo {
            get {
                return ResourceManager.GetString("LabelClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LabelClose {
            get {
                return ResourceManager.GetString("LabelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tickets.
        /// </summary>
        public static string LabelCloseTicket {
            get {
                return ResourceManager.GetString("LabelCloseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string LabelColor {
            get {
                return ResourceManager.GetString("LabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string LabelCompanyName {
            get {
                return ResourceManager.GetString("LabelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string LabelConnectionTest {
            get {
                return ResourceManager.GetString("LabelConnectionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenance.
        /// </summary>
        public static string LabelContenance {
            get {
                return ResourceManager.GetString("LabelContenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the product button.
        /// </summary>
        public static string LabelCreateProductButton {
            get {
                return ResourceManager.GetString("LabelCreateProductButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string LabelCurrency {
            get {
                return ResourceManager.GetString("LabelCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - the date has not changed! Restart in administrator mode.
        /// </summary>
        public static string LabelDataError {
            get {
                return ResourceManager.GetString("LabelDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data loading.
        /// </summary>
        public static string LabelDataLoading {
            get {
                return ResourceManager.GetString("LabelDataLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date updated.
        /// </summary>
        public static string LabelDateUpdate {
            get {
                return ResourceManager.GetString("LabelDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string LabelDevisWeb {
            get {
                return ResourceManager.GetString("LabelDevisWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string LabelDiscount {
            get {
                return ResourceManager.GetString("LabelDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cards.
        /// </summary>
        public static string LabelDiscountCard {
            get {
                return ResourceManager.GetString("LabelDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelEst {
            get {
                return ResourceManager.GetString("LabelEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess.
        /// </summary>
        public static string LabelExcess {
            get {
                return ResourceManager.GetString("LabelExcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string LabelFIO {
            get {
                return ResourceManager.GetString("LabelFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string LabelFunction {
            get {
                return ResourceManager.GetString("LabelFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string LabelGroup {
            get {
                return ResourceManager.GetString("LabelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supreme.
        /// </summary>
        public static string LabelHighter {
            get {
                return ResourceManager.GetString("LabelHighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string LabelImage {
            get {
                return ResourceManager.GetString("LabelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important functions.
        /// </summary>
        public static string LabelImportantFunctions {
            get {
                return ResourceManager.GetString("LabelImportantFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number format is invalid.
        /// </summary>
        public static string LabelInvalidNumberFormat {
            get {
                return ResourceManager.GetString("LabelInvalidNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelLocalOpeningKey {
            get {
                return ResourceManager.GetString("LabelLocalOpeningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        public static string LabelLogonError {
            get {
                return ResourceManager.GetString("LabelLogonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string LabelNameNation {
            get {
                return ResourceManager.GetString("LabelNameNation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name place arround.
        /// </summary>
        public static string LabelNamePlaceArround {
            get {
                return ResourceManager.GetString("LabelNamePlaceArround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string LabelNew {
            get {
                return ResourceManager.GetString("LabelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New total.
        /// </summary>
        public static string LabelNewTotal {
            get {
                return ResourceManager.GetString("LabelNewTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string LabelNofFound {
            get {
                return ResourceManager.GetString("LabelNofFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not have permission.
        /// </summary>
        public static string LabelNotPermission {
            get {
                return ResourceManager.GetString("LabelNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string LabelNow {
            get {
                return ResourceManager.GetString("LabelNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° cashbox.
        /// </summary>
        public static string LabelNumberCashBox {
            get {
                return ResourceManager.GetString("LabelNumberCashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° check.
        /// </summary>
        public static string LabelNumberCheck {
            get {
                return ResourceManager.GetString("LabelNumberCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumPad.
        /// </summary>
        public static string LabelNumpad {
            get {
                return ResourceManager.GetString("LabelNumpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string LabelOld {
            get {
                return ResourceManager.GetString("LabelOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string LabelOpen {
            get {
                return ResourceManager.GetString("LabelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened by.
        /// </summary>
        public static string LabelOpenedBy {
            get {
                return ResourceManager.GetString("LabelOpenedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смена открыта.
        /// </summary>
        public static string LabelOpenLocal {
            get {
                return ResourceManager.GetString("LabelOpenLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса открыта.
        /// </summary>
        public static string LabelOpenTotalTW {
            get {
                return ResourceManager.GetString("LabelOpenTotalTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Means of payment.
        /// </summary>
        public static string LabelPaymentMeans {
            get {
                return ResourceManager.GetString("LabelPaymentMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay products.
        /// </summary>
        public static string LabelPayProduct {
            get {
                return ResourceManager.GetString("LabelPayProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp pay products.
        /// </summary>
        public static string LabelPayProductTmp {
            get {
                return ResourceManager.GetString("LabelPayProductTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string LabelPermissions {
            get {
                return ResourceManager.GetString("LabelPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The piece(s) can not be a fractional number.
        /// </summary>
        public static string LabelPieceNotFractional {
            get {
                return ResourceManager.GetString("LabelPieceNotFractional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece or kg.
        /// </summary>
        public static string LabelPieceOrKg {
            get {
                return ResourceManager.GetString("LabelPieceOrKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin code.
        /// </summary>
        public static string LabelPin {
            get {
                return ResourceManager.GetString("LabelPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while loading !.
        /// </summary>
        public static string LabelPleaseWaitWhileLoading {
            get {
                return ResourceManager.GetString("LabelPleaseWaitWhileLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelPost {
            get {
                return ResourceManager.GetString("LabelPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string LabelPostalCode {
            get {
                return ResourceManager.GetString("LabelPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price with VAT.
        /// </summary>
        public static string LabelPrixTTC {
            get {
                return ResourceManager.GetString("LabelPrixTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string LabelProduct {
            get {
                return ResourceManager.GetString("LabelProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string LabelProductNotFind {
            get {
                return ResourceManager.GetString("LabelProductNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product removed.
        /// </summary>
        public static string LabelProductRemoved {
            get {
                return ResourceManager.GetString("LabelProductRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string LabelProducts {
            get {
                return ResourceManager.GetString("LabelProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        public static string LabelProviders {
            get {
                return ResourceManager.GetString("LabelProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        public static string LabelQty {
            get {
                return ResourceManager.GetString("LabelQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string LabelQuestion {
            get {
                return ResourceManager.GetString("LabelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        public static string LabelRest {
            get {
                return ResourceManager.GetString("LabelRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by EAN bar code.
        /// </summary>
        public static string LabelSearchByEAN {
            get {
                return ResourceManager.GetString("LabelSearchByEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select product.
        /// </summary>
        public static string LabelSelectProduct {
            get {
                return ResourceManager.GetString("LabelSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server time.
        /// </summary>
        public static string LabelServerTime {
            get {
                return ResourceManager.GetString("LabelServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string LabelStock {
            get {
                return ResourceManager.GetString("LabelStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subgroup.
        /// </summary>
        public static string LabelSubgroup {
            get {
                return ResourceManager.GetString("LabelSubgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare.
        /// </summary>
        public static string LabelTare {
            get {
                return ResourceManager.GetString("LabelTare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text.
        /// </summary>
        public static string LabelTextColor {
            get {
                return ResourceManager.GetString("LabelTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelTicketR {
            get {
                return ResourceManager.GetString("LabelTicketR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelTicketRetour {
            get {
                return ResourceManager.GetString("LabelTicketRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string LabelTotal {
            get {
                return ResourceManager.GetString("LabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LabelTotalOpeningKey {
            get {
                return ResourceManager.GetString("LabelTotalOpeningKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelType {
            get {
                return ResourceManager.GetString("LabelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pays types.
        /// </summary>
        public static string LabelTypesPays {
            get {
                return ResourceManager.GetString("LabelTypesPays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of VAT.
        /// </summary>
        public static string LabelTypeVat {
            get {
                return ResourceManager.GetString("LabelTypeVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit contenance.
        /// </summary>
        public static string LabelUnitContenance {
            get {
                return ResourceManager.GetString("LabelUnitContenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string LabelVat {
            get {
                return ResourceManager.GetString("LabelVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing.
        /// </summary>
        public static string LabelViewing {
            get {
                return ResourceManager.GetString("LabelViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string LabelXmlFile {
            get {
                return ResourceManager.GetString("LabelXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group products.
        /// </summary>
        public static string MenuGroupsProduct {
            get {
                return ResourceManager.GetString("MenuGroupsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string MenuRoles {
            get {
                return ResourceManager.GetString("MenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync settings.
        /// </summary>
        public static string MenuSyncSetting {
            get {
                return ResourceManager.GetString("MenuSyncSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string MenuUsers {
            get {
                return ResourceManager.GetString("MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VATs.
        /// </summary>
        public static string MenuVats {
            get {
                return ResourceManager.GetString("MenuVats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сonfirm the deletion.
        /// </summary>
        public static string MessageDeleteQuestion {
            get {
                return ResourceManager.GetString("MessageDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is administrator.
        /// </summary>
        public static string MessageIsAdmin {
            get {
                return ResourceManager.GetString("MessageIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit all.
        /// </summary>
        public static string PermissionAll {
            get {
                return ResourceManager.GetString("PermissionAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission delete product from check.
        /// </summary>
        public static string PermissionDeleteProductFromCheck {
            get {
                return ResourceManager.GetString("PermissionDeleteProductFromCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission editing of buttons.
        /// </summary>
        public static string PermissionRedactButton {
            get {
                return ResourceManager.GetString("PermissionRedactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission editing groups of products.
        /// </summary>
        public static string PermissionRedactGroupsProduct {
            get {
                return ResourceManager.GetString("PermissionRedactGroupsProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission editing of roles.
        /// </summary>
        public static string PermissionRedactRole {
            get {
                return ResourceManager.GetString("PermissionRedactRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sync settings.
        /// </summary>
        public static string PermissionRedactSync {
            get {
                return ResourceManager.GetString("PermissionRedactSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission editing of users.
        /// </summary>
        public static string PermissionRedactUser {
            get {
                return ResourceManager.GetString("PermissionRedactUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission editing VAT.
        /// </summary>
        public static string PermissionRedactVat {
            get {
                return ResourceManager.GetString("PermissionRedactVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions of cashbox.
        /// </summary>
        public static string TabCashFunctions {
            get {
                return ResourceManager.GetString("TabCashFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display settings.
        /// </summary>
        public static string TabDisplaySettings {
            get {
                return ResourceManager.GetString("TabDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string TabProducts {
            get {
                return ResourceManager.GetString("TabProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick payment methods.
        /// </summary>
        public static string TabQuickPaymentsMethods {
            get {
                return ResourceManager.GetString("TabQuickPaymentsMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank card.
        /// </summary>
        public static string TypePayBankCards {
            get {
                return ResourceManager.GetString("TypePayBankCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string TypePayBankChecks {
            get {
                return ResourceManager.GetString("TypePayBankChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bond.
        /// </summary>
        public static string TypePayBondAchat {
            get {
                return ResourceManager.GetString("TypePayBondAchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string TypePayCash {
            get {
                return ResourceManager.GetString("TypePayCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resto card.
        /// </summary>
        public static string TypePayResto {
            get {
                return ResourceManager.GetString("TypePayResto", resourceCulture);
            }
        }
    }
}
